[package]
name = "polkadot-validation"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.1.17"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.17", features = ["compat"] }
futures-timer = "0.2.1"
parking_lot = "0.7.1"
tokio = "0.1.7"
derive_more = "0.14.0"
log = "0.4.6"
exit-future = "0.1"
parity-codec = "4.1"
extrinsic_store = { package = "polkadot-availability-store", path = "../availability-store" }
parachain = { package = "polkadot-parachain", path = "../parachain" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
table = { package = "polkadot-statement-table", path = "../statement-table" }
aura = { package = "substrate-consensus-aura", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
aura_primitives = { package = "substrate-consensus-aura-primitives", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
consensus = { package = "substrate-consensus-common", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
runtime_aura = { package = "srml-aura", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
trie = { package = "substrate-trie", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }

[dev-dependencies]
substrate-keyring = { git = "https://github.com/paritytech/substrate", branch = "gav-ext-tx-call" }
